### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by danielbaak** [webpack-contrib/null-loader#6]
Hi, 

can you please add a usage example to the Readme? 

Thanks!

**Comment by michael-ciniawsky** [comment]
@danielbaak Yep will do, if you find a good example somewhere else meanwhile feel free to send a quick PR 😛

**Comment by xsynaptic** [comment]
I found a use case but I'm not sure if it's useful to document... and I'm a little new to Webpack so don't wanna go throwing PRs around all willy-nilly. I can formalize this if it sounds okay:

I'm transpiling the ES6 source of Choices.js which imports its own [polyfill bundle](https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/lib/polyfills.js). Since I already manage polyfills for my main app this chunk of code adds no value. I can use `null-loader` with a simple `test` for the absolute path to the polyfill bundle in Choices.js and it will be knocked out, so to speak, without causing any loss in functionality.

**Comment by michael-ciniawsky** [comment]
@synapticism Send PR for discussion please 😛

**Comment by michael-ciniawsky** [comment]
@evilebottnawi Yep I rework the README's atm anyways and according the our standard template for the docs page, there **must* be an example included, feel free to close
